import usermodel from "../models/user.model.js";
import jwt from "jsonwebtoken";

export const authmiddleware = async (req, res, next) => {
  // On requests, the client sends its authentication token,
  // commonly through the Authorization header.

  // req.headers.authorization retrieves the Authorization header
  // so we can extract and verify the token.
  const authHeader = req.headers.authorization;

  if (!authHeader) {
    return res.status(401).json({
      message: "Token not found",
    });
  }

  // jwt.decode is used to decode the token form the user
  //   const data = jwt.decode(authHeader);

  //    const data = jwt.verify(token,jwt_secret) -> this will verify the token , that if its generated by the same server or not ,if not then will throw an error

  const data = jwt.verify(authHeader, process.env.JWT_SECRET);

  const user = await usermodel.findById(data.id);
  console.log(user);

  // Attach the authenticated user's data to the request object.
  
  // `req` is the request object created by Express. We can add our own
  // properties to it, so here we create a new `req.user` property and
  // store the user we found from the database.
    
  // This allows the next middleware/controller to access the logged-in
  // user's information through `req.user`.
  req.user = user;

  // `next()` tells Express:
  // "This middleware has finished its job. Move on to the next
  // middleware or route handler in the request pipeline."
  //
  // Without `next()`, the request stops here and the client will keep
  // waiting (unless this middleware sends a response itself).
  next();
};
